import 'dart:async';

import 'package:floor/floor.dart';
// Required by the generated code.
import 'package:sqflite/sqflite.dart' as sqflite;

import 'converters/date_time_converters.dart';
import 'dao/note_dao.dart';
import 'entities/note.dart';

part 'app_database.g.dart';

/// The single SQLite database of the app (Floor abstraction layer).
///
/// Create **one** instance at start up with [openNotesDatabase] and share it
/// with the service layer; a second instance would mean a second connection.
@Database(entities: [Note], version: 2)
abstract class AppDatabase extends FloorDatabase {
  /// Injected by Floor's code generator.
  NoteDao get noteDao;
}

/// Name of the SQLite file inside the platform database directory.
const String notesDatabaseName = 'notes.db';

/// Schema history, kept in one place so a migration is easy to follow.
///
/// * v1 — `notes` table with text, location columns and timestamps.
/// * v2 — adds `place_name`, the reverse geocoded location name.
Future<void> _upgradeFrom1To2(sqflite.Database database) async {
  await database.execute('ALTER TABLE notes ADD COLUMN place_name TEXT');
}

/// Opens the notes database, creating the `notes` table on first run.
///
/// The schema, the migration hooks and the query adapters are all generated by
/// Floor, so this method only decides *where* the file lives.
///
/// [filePath] can point the database at a different file. The tests use it to
/// verify that the notes really survive a restart.
Future<AppDatabase> openNotesDatabase({String? filePath}) {
  return $FloorAppDatabase
      .databaseBuilder(filePath ?? notesDatabaseName)
      .addMigrations([Migration(1, 2, _upgradeFrom1To2)])
      .addCallback(
        Callback(onConfigure: (sqflite.Database database) {
          // Keeps SQLite honest about foreign keys and cascades.
          database.execute('PRAGMA foreign_keys = ON');
        }),
      )
      .build();
}

/// Opens a private in-memory database. Used by the unit and widget tests so
/// they never read or write a real file.
Future<AppDatabase> openInMemoryNotesDatabase() {
  return $FloorAppDatabase.inMemoryDatabaseBuilder().build();
}