import 'package:floor/floor.dart';

import '../converters/date_time_converters.dart';

/// Immutable value object describing *where* a note was written.
///
/// SQLite cannot store Dart objects directly, so the fields of this class are
/// flattened into nullable columns on the `notes` table:
///  * latitude / longitude -> `REAL`
///  * accuracy             -> `REAL` (meters)
///  * placeName            -> `TEXT` (reverse geocoded, e.g. "Dokki, Giza")
///  * capturedAt           -> `INTEGER` (epoch milliseconds)
///
/// A note has a location only when **both** latitude and longitude are known.
/// [placeName] is a *nice to have*: when reverse geocoding fails the note is
/// still stored with its coordinates and [displayText] falls back to them.
class NoteLocation {
  const NoteLocation({
    required this.latitude,
    required this.longitude,
    this.accuracy,
    this.placeName,
    this.capturedAt,
  });

  final double latitude;
  final double longitude;
  final double? accuracy;

  /// Reverse geocoded, human readable name such as `Dokki, Giza, Egypt`.
  /// `null` when the lookup failed or was skipped.
  final String? placeName;

  final DateTime? capturedAt;

  /// Human readable coordinates, e.g. `30.044420, 31.235712`.
  String get coordinates =>
      '${latitude.toStringAsFixed(6)}, ${longitude.toStringAsFixed(6)}';

  /// `true` when a readable name is available.
  bool get hasPlaceName => (placeName ?? '').trim().isNotEmpty;

  /// What the UI shows first: the place name when there is one.
  String get title => hasPlaceName ? placeName!.trim() : 'Location available';

  /// Secondary, less prominent line: the coordinates and the accuracy.
  String get coordinatesLabel => accuracy == null
      ? coordinates
      : '$coordinates  •  ±${accuracy!.round()} m';

  /// Full one line summary used where only a single line fits, e.g.
  /// `Dokki, Giza (±12 m)`.
  String get displayText => hasPlaceName
      ? (accuracy == null ? title : '$title (±${accuracy!.round()} m)')
      : coordinatesLabel;

  NoteLocation copyWith({
    double? latitude,
    double? longitude,
    double? accuracy,
    String? placeName,
    bool clearPlaceName = false,
    DateTime? capturedAt,
  }) {
    return NoteLocation(
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      accuracy: accuracy ?? this.accuracy,
      placeName: clearPlaceName ? null : (placeName ?? this.placeName),
      capturedAt: capturedAt ?? this.capturedAt,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is NoteLocation &&
      other.latitude == latitude &&
      other.longitude == longitude &&
      other.accuracy == accuracy &&
      other.placeName == placeName &&
      other.capturedAt == capturedAt;

  @override
  int get hashCode =>
      Object.hash(latitude, longitude, accuracy, placeName, capturedAt);

  @override
  String toString() => 'NoteLocation($displayText)';
}

/// A single note row of the `notes` table.
///
/// [id] is `null` for a note that has not been inserted yet; SQLite assigns the
/// value through the `AUTOINCREMENT` primary key when the row is written.
@Entity(tableName: 'notes')
@TypeConverters([DateTimeConverter, NullableDateTimeConverter])
class Note {
  const Note({
    this.id,
    required this.text,
    this.latitude,
    this.longitude,
    this.locationAccuracy,
    this.placeName,
    this.locationCapturedAt,
    required this.createdAt,
    required this.updatedAt,
  });

  /// `INTEGER PRIMARY KEY AUTOINCREMENT` — generated by SQLite on insert.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  /// `TEXT NOT NULL` — the note content. Always trimmed before saving.
  @ColumnInfo(name: 'note_text')
  final String text;

  /// `REAL` (nullable) — latitude in degrees, -90..90.
  @ColumnInfo(name: 'latitude')
  final double? latitude;

  /// `REAL` (nullable) — longitude in degrees, -180..180.
  @ColumnInfo(name: 'longitude')
  final double? longitude;

  /// `REAL` (nullable) — horizontal accuracy in meters.
  @ColumnInfo(name: 'location_accuracy')
  final double? locationAccuracy;

  /// `TEXT` (nullable) — reverse geocoded name of the place, when available.
  @ColumnInfo(name: 'place_name')
  final String? placeName;

  /// `INTEGER` (nullable) — when the location was captured (epoch ms).
  @ColumnInfo(name: 'location_captured_at')
  final DateTime? locationCapturedAt;

  /// `INTEGER NOT NULL` — creation time (epoch ms, UTC).
  @ColumnInfo(name: 'created_at')
  final DateTime createdAt;

  /// `INTEGER NOT NULL` — last modification time (epoch ms, UTC).
  @ColumnInfo(name: 'updated_at')
  final DateTime updatedAt;

  /// `true` when the note carries usable coordinates.
  bool get hasLocation => latitude != null && longitude != null;

  /// The location of the note, or `null` when it has none.
  NoteLocation? get location {
    if (!hasLocation) return null;
    return NoteLocation(
      latitude: latitude!,
      longitude: longitude!,
      accuracy: locationAccuracy,
      placeName: placeName,
      capturedAt: locationCapturedAt,
    );
  }

  Note copyWith({
    int? id,
    String? text,
    double? latitude,
    double? longitude,
    double? locationAccuracy,
    String? placeName,
    DateTime? locationCapturedAt,
    bool clearLocation = false,
    bool clearId = false,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return Note(
      id: clearId ? null : (id ?? this.id),
      text: text ?? this.text,
      latitude: clearLocation ? null : (latitude ?? this.latitude),
      longitude: clearLocation ? null : (longitude ?? this.longitude),
      locationAccuracy: clearLocation
          ? null
          : (locationAccuracy ?? this.locationAccuracy),
      placeName: clearLocation ? null : (placeName ?? this.placeName),
      locationCapturedAt: clearLocation
          ? null
          : (locationCapturedAt ?? this.locationCapturedAt),
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is Note &&
      other.id == id &&
      other.text == text &&
      other.latitude == latitude &&
      other.longitude == longitude &&
      other.locationAccuracy == locationAccuracy &&
      other.placeName == placeName &&
      other.locationCapturedAt == locationCapturedAt &&
      other.createdAt == createdAt &&
      other.updatedAt == updatedAt;

  @override
  int get hashCode => Object.hash(
    id,
    text,
    latitude,
    longitude,
    locationAccuracy,
    placeName,
    locationCapturedAt,
    createdAt,
    updatedAt,
  );

  @override
  String toString() => 'Note(id: $id, text: $text, hasLocation: $hasLocation)';
}